enum GameState {
  START, COUNTDOWN1, COUNTDOWN2, COUNTDOWN3, FLIPPEDCOUNTDOWN1, FLIPPEDCOUNTDOWN2, FLIPPEDCOUNTDOWN3, CALIBRATE1, CALIBRATE2, CALIBRATE3, BETWEENLEVEL, PLAY, LOSE, FLOSE, WIN, RESET
};


